version: '3.9'

services:
  flask-app:
    build: .
    image: flask-app-image:dev
    container_name: flask-app-container.dev
    ports:
      - "81:80"  
    environment:
      - FLASK_ENV=development  